//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int UFID { get; set; }
        public string departmentTitle { get; set; }
        public string courseName { get; set; }
    
        public virtual user user { get; set; }
    }
}
