//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.Courses = new HashSet<Cours>();
            this.EducationSections = new HashSet<EducationSection>();
            this.reservations = new HashSet<reservation>();
            this.reservations1 = new HashSet<reservation>();
            this.userSchedules = new HashSet<userSchedule>();
        }
    
        public int UFID { get; set; }
        public string fullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<double> requestedPay { get; set; }
        public Nullable<bool> isTutor { get; set; }
        public Nullable<double> averageRating { get; set; }
        public string shortBio { get; set; }
        public string Biography { get; set; }
        public string pictureSource { get; set; }
        public string zoomLink { get; set; }
        public string salt { get; set; }
        public string stripeAccountID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cours> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationSection> EducationSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userSchedule> userSchedules { get; set; }
    }
}
